# Id fijo de la única fila que tiene (y va a tener) esta tabla.
ID_CONFIGURACION_SISTEMA = 1

DIAS_ANTELACION_VENCIMIENTO_DEFAULT = 15
HORA_GENERACION_CHECKLISTS_DEFAULT = 7
MINUTO_GENERACION_CHECKLISTS_DEFAULT = 0
